language: node_js
node_js:
  - "node"
  - "iojs"
before_script:
  - npm install -g gulp
script: gulp
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
